version: '2'

services:
  app:
    image: ubuntu:20.04
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - my-network
    depends_on:
      - postgres-task-manager
  postgres-task-manager:
    image: postgres:14.1-alpine
    container_name: postgres-task-manager
    build:
      context: .
      dockerfile: ./Postgresql_Dockerfile
    ports:
      - 5432:5432
    networks:
      - my-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

networks:
  my-network:
    driver: bridge
